### ISSUE TITLE
zerocopy: ByteOrder-specific validation of Enums

### ISSUE THREAD

**Issue by jtsylve** [udoprog/musli#167]
I'm trying to determine if it is currently possible to take ByteOrder into account when validating enums.  Unless I'm missing something, the current validation code seems to validate enum variants without respect to byte order.  When parsing structures that contain enumerations on non-native endian data, this validation will fail.   For example, `Endian<SomeEnum, Little>` and `Endian<SomeEnum, Big>` generate the same validation logic.

**Comment by udoprog** [comment]
The `ByteOrder` in use shouldn't affect which bit-patterns are or are not valid (as Rust defines valid), it should only determine whether the bits for any affected nested fields should be byte order swapped or not.

It's been a minute since I looked over the implementation, what specifically do you have issues with?

**Comment by jtsylve** [comment]
It's certainly possible that I'm doing something wrong.

The following code panics

```rust
    #[derive(ZeroCopy, PartialEq, Debug, Clone, Copy)]
    #[repr(u32)]
    enum SomeEnum {
        A = 1,
        B = 2,
    }
    
    #[derive(ZeroCopy, Debug, Clone, Copy)]
    #[repr(C)]
    struct SomeStructBE {
        a: Endian<u32, Big>,
        b: Endian<SomeEnum, Big>,
    }
    
    #[test]
    fn test_from_bytes_be() {
        let data: Vec<u8> = vec![0, 0, 0, 1, 0, 0, 0, 2];

        let struct_be = SomeStructBE::from_bytes(&data).unwrap();

        assert_eq!(struct_be.a.to_ne(), 1);
        assert_eq!(struct_be.b.to_ne(), SomeEnum::B);
    }
```
    
```
    called `Result::unwrap()` on an `Err` value: Error { kind: IllegalDiscriminant { name: "byteorder::test::SomeEnum", discriminant: Repr { kind: U32(33554432) } } }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1077:23
   4: byteorder::test::test_from_bytes_be
             at ./tests/byteorder.rs:48:25
   5: byteorder::test::test_from_bytes_be::{{closure}}
             at ./tests/byteorder.rs:38:28
   6: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
```

This passes when I would expect it to fail.


```rust
    #[test]
    fn test_from_bytes_be() {
        let data: Vec<u8> = vec![0, 0, 0, 1, 2, 0, 0, 0];

        let struct_be = SomeStructBE::from_bytes(&data).unwrap();

        assert_eq!(struct_be.a.to_ne(), 1);
        assert_eq!(struct_be.b.to_ne(), SomeEnum::B);
    }
```

**Comment by udoprog** [comment]
Aha tricky!

So in order to construct a reference `SomeStructBE`, all of its fields must have inhabitable bit-patterns the way Rust defines them. The `Endian<SomeEnum, T>` marker doesn't actually change anything about the representation of the field. The only purpose of field validation is to ensure that the bits that are being presented can be inhabited by the type `SomeEnum`. If we changed something, it would no longer be "zero copy".

First off, to make validation pass, what you need is to define a more variants in the enum so it can inhabit the byte-swapped representations as well:

```rust
#[derive(ZeroCopy, PartialEq, Debug, Clone, Copy)]
#[repr(u32)]
enum SomeEnum {
    A = 1,
    B = 2,
    A_ = 1u32.swap_bytes(),
    B_ = 2u32.swap_bytes(),
}
```

Now the call to `from_bytes` should work. *However*, byte swapping with `.to_ne` does not, so after calling it you'll see the wrong variant `B_` instead of `B`.

This is in my mind a bug, attempting to byte swap should preferably not compile with a const assert against `T::CAN_SWAP_BYTES` or a limitation in the library where byte swapping should be possible if all the byte-swapped bit-patterns are supported.

**Comment by udoprog** [comment]
I've started tinkering with it in https://github.com/udoprog/musli/pull/168

**Comment by udoprog** [comment]
I've fixed the issue of byte-swapping enums, and included some examples and tests in #168, please look them over and tell me if it makes sense.

**Comment by jtsylve** [comment]
I see what you're going for here, and it's a neat solution, but I wonder if it makes enums a bit more difficult to use than is needed.  It would also add (invalid) variants to the enum's definition, which might cause linting issues about non-exhaustive use of match cases.

I wonder if it might be better to just make enums unswappable, and use attribute macros to define (or re-define) the values at compile time.

```rust
#[derive(ZeroCopy, PartialEq, Debug, Clone, Copy)]
#[zero_copy(big_endian)]
#[repr(u32)]
enum Enum {
    A = 1,
    B = 2,
}
```

Would be converted to this on little-endian systems

```rust
#[repr(u32)]
enum Enum {
    A = u32::swap_bytes(1),
    B = u32::swap_bytes(2),
}
```

and this on big-endian systems

```rust
#[repr(u32)]
enum Enum {
    A = 1,
    B = 2,
}
```

**Comment by jtsylve** [comment]
I suppose an alternative idea is to generate both definitions of enums and swap_bytes, swaps the bytes and returns the other type.

**Comment by udoprog** [comment]
> I wonder if it might be better to just make enums unswappable, and use attribute macros to define (or re-define) the values at compile time.

With the new changes this is the status quo, if you don't add the `swap_bytes` attribute to an enum, it will not try to generate a valid `swap_bytes` implementation and `CAN_SWAP_BYTES` will be set to `false` which will cause the `Endian` helper to not compile when used.

I think what you're looking for is something which makes this pattern simpler if you only want to support big endianness (this is a no-op on big-endian systems):

```rust
#[repr(u32)]
enum Enum {
    A = u32::to_be(1),
    B = u32::to_be(2),
}
```

I'm just not sure there are many improvements to be made over the above. Derive macros cannot modify the type, so we can't modify the enum representation transparently. That means we'd have to use an attribute macro that rewrites the type which comes with its own headaches. You'd not be able to use the `Endian<Enum, T>` helper on the above enum. There is just no way for it to inhabit all valid bit-patterns it would require to support byte-swapping.

> I suppose an alternative idea is to generate both definitions of enums and swap_bytes, swaps the bytes and returns the other type.

This seems like something you might want to use a higher level abstraction for. It's more in the realm of "decoding" in my mind.

**Comment by jtsylve** [comment]
How often do you release new versions?  I'd like to try out these changes.

**Comment by udoprog** [comment]
I'll ship a new version right away. Thanks!

**Comment by udoprog** [comment]
I'm not sure what else we can do, but the immediate bug has been solved. So closing.
