### ISSUE TITLE
Macros should use Result and Option through fully qualified names

### ISSUE THREAD

**Issue by AaronKutch** [udoprog/musli#20]
The first example on https://docs.rs/musli/0.0.49/musli/derives/index.html does not build. I ran `cargo test --doc` locally and noticed there were three `ignored` tests which included this failing one, so I presume there is a config somewhere to ignore it. Just putting `#[derive(Encode, Decode)]` on any struct seems to result in "type alias takes 1 generic argument but 2 generic arguments were supplied" errors for me. What is going on here?

**Comment by udoprog** [comment]
Yeah, some macros are old and we might've missed subtle things like that. Thanks for the report!
