### ISSUE TITLE
musli-json field skip doesn't work correctly

### ISSUE THREAD

**Issue by l4l** [udoprog/musli#28]
MRE:

```rust
#[derive(Debug, Encode, Decode)]
#[musli(default_field_name = "name")]
struct T {
    a: f64,
}

musli_json::from_slice::<T>(r#"{"x":"1","a":1.3}"#.as_bytes()).unwrap();
```

Works, if skipped field is not a string, e.g `"x":1`. Same if appended to the end.

**Comment by udoprog** [comment]
This makes me want to extend the test suite to randomly inject whitespace (for formats which support it). Cheers!
